In [17]:
# Organizar la informacion 
# Se recorre el archivo "review.json" para construir nuevos .csv  
#  clasificando por año, se identifico que la data va desde 2005 hasta 2022, 
#  por lo tanto se tendran 17 archivos de la forma ... review2019.csv, review2020.csv ... 
# nota = En la carpeta donde se ejecuta debe estar el archivo "review.json" y 
#        no deben estar archivos review20XX.csv de corridas anteriores

import pandas as pd 
from IPython.display import clear_output
import os 

def cargaIncremental(df,nombre ='review'):
    df['date'] = pd.to_datetime(df['date'])
    for year in range(2005,2023):
        if os.path.isfile(nombre+"_"+str(year)+".csv"):
            #Carga incremental de datos en .csv
            print('actualizando '+nombre+"_"+str(year)+".csv")
            filtered_df = df.loc[df['date'].dt.year == year]
            filtered_df.to_csv(nombre+"_"+str(year)+".csv",mode='a', index=False, header=False)
        else:
            #Primera corrida
            print('creando '+nombre+"_"+str(year)+".csv")
            filtered_df = df.loc[df['date'].dt.year == year]
            filtered_df.to_csv(nombre+"_"+str(year)+".csv",index=False)


nombre = 'review' 
total = 0 
cont = 0
cont_max = 35  #Se sabe que tamaño +200k  se haran 35 partes (chunk) del .json 

Tamano = 200000
# Se recorre por partes el archivo .json
for chunk in pd.read_json(nombre+".json",chunksize=Tamano, lines=True):
        # Visualizacion de avance
        cont = cont + 1
        clear_output(wait=True)
        print('Completado Etapa 1: '+nombre+str(cont)+ "  "+ str(round(cont / cont_max * 100, 2)) + '%')
        
        #Se carga la parte
        cargaIncremental(chunk)

cont = 0
cont_max = 18 
#Limpieza final
for year in range(2005,2023):
    # Visualizacion de avance
    cont = cont + 1
    clear_output(wait=True)
    print('Completado Etapa 2: '+str(cont)+"/"+str(cont_max)+"  "+ str(round(cont / cont_max * 100, 2)) + '%')
    
    if os.path.isfile(nombre+"_"+str(year)+".csv"):
        #Revision de datos en .csv
        df = pd.read_csv(nombre+"_"+str(year)+".csv") 
        filtered_df = df.drop_duplicates().reset_index(drop=True)
        filtered_df.to_csv(nombre+"_"+str(year)+".csv",index=False)

Completado Etapa 2: 18/18  100.0%

In [18]:
df = pd.read_csv('review_2018.csv')
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906362 entries, 0 to 906361
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    906362 non-null  object
 1   user_id      906362 non-null  object
 2   business_id  906362 non-null  object
 3   stars        906362 non-null  int64
 4   useful       906362 non-null  int64
 5   funny        906362 non-null  int64
 6   cool         906362 non-null  int64
 7   text         906362 non-null  object
 8   date         906362 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 62.2+ MB

In [19]:
df.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,lUUhg8ltDsUZ9h0xnwY4Dg,RreNy--tOmXMl1en0wiBOg,cPepkJeRMtHapc_b2Oe_dw,4,1,0,1,I was really between 3 and 4 stars for this on...,2018-07-17 03:30:07
2,JBWZmBy69VMggxj3eYn17Q,aFa96pz67TwOFu4Weq5Agg,kq5Ghhh14r-eCxlVmlyd8w,5,0,0,0,My boyfriend and I tried this deli for the fir...,2018-08-23 21:39:38
3,E9AB7V4z8xrt2uPF7T55FQ,iYY5Ii1LGpZCpXFkHlMefw,Zx7n8mdt8OzLRXVzolXNhQ,5,0,0,0,Amazing biscuits and (fill in the blank). Grea...,2018-04-27 23:03:21
4,A4n4YaE-owOVgTQcrVqHUw,S7bjj-L07JuRr-tpX1UZLw,I6L0Zxi5Ww0zEWSAVgngeQ,4,0,0,0,The cafe was extremely cute. We came at 8am an...,2018-07-07 20:50:12